### ISSUE TITLE
user documentation not correct

### ISSUE THREAD

**Issue by gvseghbr** [tengu-team/layer-sojobo#10]
E.g. there is no access attribute in the `/users/{user}` response.
And even more important, where is the type attribute of the controllers??

**Comment by mhmoerma** [comment]
Type attribute of a controller is visible when doing a GET call on `/tengu/controllers/{controller}`

**Comment by mhmoerma** [comment]
fixed: https://github.com/tengu-team/layer-sojobo/commit/aca3e6c33487c2faa25b1f42a071d0667e75b0e0
