### ISSUE TITLE
Model response not correct

### ISSUE THREAD

**Issue by gvseghbr** [tengu-team/layer-sojobo#12]
The `juju-gui-url` is not correctly formatted. It has 2 ports.

**Comment by gvseghbr** [comment]
The `ssh-keys` also has strange content. If there is no SSH keys set, the result should be an empty list or something similar.

**Comment by mhmoerma** [comment]
Do you have an example of the ssh-output?

**Comment by mhmoerma** [comment]
Fixed: https://github.com/tengu-team/layer-sojobo/commit/c4be84e910e20c778ff9f6c22407cded2614a12b
