### ISSUE TITLE
Does this delete all SSH-keys? Not a good idea ;)

### ISSUE THREAD

**Issue by gvseghbr** [tengu-team/layer-sojobo#35]
https://github.com/tengu-team/layer-sojobo/blob/0e338108a87bc41e1128bb03d3626d2d52c7d93f/files/sojobo_api/api/api_users.py#L165

Should refer to a particular index, e.g. `DELETE /users/{user}/ssh-keys/1`

**Comment by gvseghbr** [comment]
OK, looked a bit more in depth to the code. As it is now, it makes more sense to do updates of the `ssh-keys` with a PUT to `/users/{user}/ssh-keys`. This to both add and remove ssh-keys. It will of course become tricky to delete the correct ssh-keys. Perhaps we need to add the key's _fingerprints_ to the DS.

**Comment by sebastienpattyn93** [comment]
Is it necessary to update an ssh-key? I thought that we were going to only allow adding and removing ssh-keys for a user. 

I will take a look to add the fingerprint ssh-key into the DS and return it when get-ssh-keys is called

**Comment by gvseghbr** [comment]
It's not really updating a particular ssh-key, but more updating the list of ssh-keys.

**Comment by sebastienpattyn93** [comment]
There is now 1 call to update the ssh list for a certain user. A list of ssh-keys will be passed and will check if new keys will have to be added or old keys will have to be removed. This will be done in a background process. In the API there will be a check if this user had the right to update the ssh-keys.
