### ISSUE TITLE
Is the name of a credential the same name as we see in the model info?

### ISSUE THREAD

**Issue by gvseghbr** [tengu-team/layer-sojobo#37]
https://github.com/tengu-team/layer-sojobo/blob/0e338108a87bc41e1128bb03d3626d2d52c7d93f/files/sojobo_api/api/api_users.py#L181

And what about the other properties in the credential object?

**Comment by sebastienpattyn93** [comment]
appearantly the credential_name is no longer written to datastore. This must be a mistake since the last rewrite. Are there any other properties that should be added to redis except for the credential_name and the crefential JSON?

**Comment by sebastienpattyn93** [comment]
What other properties should there be available?
