### ISSUE TITLE
What is the response time?

### ISSUE THREAD

**Issue by gvseghbr** [tengu-team/layer-sojobo#41]
https://github.com/tengu-team/layer-sojobo/blob/0e338108a87bc41e1128bb03d3626d2d52c7d93f/files/sojobo_api/api/api_users.py#L59

The `w_juju.py` code shows this method runs over all available controllers. If it takes too long, we should move this to a background script as well.

**Comment by sebastienpattyn93** [comment]
This is indeed creating a user on all controllers and disabling where the user is not needed. This method depends on how many controllerconnections will have to be made. It will be better to start this in a backgroundprocess

**Comment by sebastienpattyn93** [comment]
This has now been moved to run as a background process. The call is returning a `202` now with the notifiaction that the user is being created
