### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by sebastienpattyn93** [tengu-team/layer-sojobo#6]
Need more advanced input validation and implement it on all the user input

**Comment by sebastienpattyn93** [comment]
The old check_input method is updated and will only be used now to check contents of the body. It was not needed to for example check the controller and or model name in a call where those are not in the body but in the url. Even after the check_input you would still get a 404 if the url does not exist. Now it will immediately return a 404 without checking for special characters

In the new check_input there is a dict that has a regex and an error message for certain keys. This way we can return the right format to the user and there will only be checks if something is created

**Comment by gvseghbr** [comment]
The method `add_credential` needs input validation. The validation depends on the controller type, so it needs to be part of the controller's subordinate.

**Comment by sebastienpattyn93** [comment]
this check only happened when bootstrapping a controller. I'll add the validation and together with issue #13 i'll remove it from the background script since this functionality is only changing values in the DS

**Comment by sebastienpattyn93** [comment]
The check if the input off the credential is right, already happens in the subordinate controller charms.
```
def add_credential(user, c_type, cred_name, credential):    
    result_cred = generate_cred_file(c_type, cred_name, credential)
    Popen(["python3.6", "{}/scripts/add_credential.py".format(settings.SOJOBO_API_DIR), user,
           settings.SOJOBO_API_DIR, str(result_cred), settings.REDIS_HOST, settings.REDIS_PORT])
```

`generate_cred_file` then calls the method from the right controller. for example google:

```
CRED_KEYS = ['type', 'project_id', 'private_key_id', 'private_key', 'client_email',
             'client_id', 'auth_uri', 'token_uri', 'auth_provider_x509_cert_url',
             'client_x509_cert_url']


def generate_cred_file(name, credentials):
    if len(CRED_KEYS) == len(list(credentials.keys())):
        for cred in CRED_KEYS:
            if not cred in list(credentials.keys()):
                error = errors.key_does_not_exist(cred)
                abort(error[0], error[1])
    result = {
        'type': 'jsonfile',
        'name': name,
        'key': {'file': str(json.dumps(credentials))}
    }
    return result
```
